### ISSUE TITLE
Clicking outside of datetimepicker reinitializes the date, unwanted behaviour

### ISSUE THREAD

**Issue by josephernest** [xdan/datetimepicker#436]
Try this ([live demo here](http://gget.it/eo94omwm/testt.html)):
Clicking outside of datetimepicker reinitializes the date to Sunday 31 December 1899. How to solve this?

```
<link rel="stylesheet" type="text/css" href="http://gget.it/ov1nuzeh/jquery.datetimepicker.css"/>
<input id="when" type="text"/>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script src="http://gget.it/dzxqdkh2/jquery.datetimepicker.full.min.js"></script>
<script>
$('#when').datetimepicker({dayOfWeekStart : 1, format:"l d F, H:i"});
</script>
```

**Comment by skainz** [comment]
HI, i had the same issues, as is wanted to get 
YYMMDD-HHMM output. I set 

`validateOnBlur: false`

and now the text stays the same after clicking otuside the input box.

Hope this helps, at least it works for me.

then it works for me.

**Comment by oshihirii** [comment]
I also had this issue and it was resolved by implementing @skainz solution.  

My code was:

    $(document).ready(function() {
    $('#date_and_time').datetimepicker({
    format:'d / m / y  @  g:i A', 
    formatTime: 'g:i A',
    theme: 'dark',
    validateOnBlur: false
    });
    });

**Comment by oshihirii** [comment]
Hmm, unfortunately, when clicking on the input again to trigger the calendar, I can see that the calendar has reset to a different month, date and year.  

For example, if I initially select `01 / 06 / 16  @  2:35 PM`, then click outside of the input, then click inside the input again, the calendar pops up with this month and year selected:

`31 / 12 / 99  @  6:00 AM`

Any ideas?

**Comment by zeeshanhive** [comment]
@oshihirii  did you reslove the error because i am still facing this error

**Comment by deepeshk79** [comment]
Is this issue resolved ? I'm still facing the same error...

**Comment by deepeshk79** [comment]
Got the solution, check the link 
[https://github.com/uxsolutions/bootstrap-datepicker/issues/1291]

The way I solved is as below i.e. using forceParse:false
`        $('.date-time-picker').datetimepicker({
            format: 'yyyy-mm-dd hh:ii',
            forceParse: false
        });
`

**Comment by nickwilliams-eventbrite** [comment]
I was also having this issue with latest versions, and I was able to solve it with `validateOnBlue: false`.

**Comment by srinudhulipalla** [comment]
I was having the same issue and fixed the same using validateOnBlur: false

**Comment by asaadmahmood** [comment]
I can still see the issue even with `validateOnBlur: false`.
